language: python
python:
  - "2.7"
# install database service
services:
  - mongodb
# install dependencies
install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install swig libxmlsec1 xmlsec1"
  - "pip install -r Ohouse/requirements.txt"
# setup environment and start Ohouse
before_script:
  - "cp Ohouse/deploy/config.json.example Ohouse/deploy/config.json"
  - "cp Ohouse/deploy/registry.json.example Ohouse/deploy/registry.json"
  - "cp Ohouse/deploy/supplementary_fields.json.example Ohouse/deploy/supplementary_fields.json"
  - "cd Ohouse && ./Ohouse/test/creds/gen-certs.sh && cd .."
  - "python Ohouse/src/main.py &"
  - "sleep 5"
# run Python unit tests
script:
  - "python Ohouse/test/unit/v2/reg_tests.py"
#  - "python Ohouse/test/unit/v2/sa_tests.py"
  - "python Ohouse/test/unit/v2/ma_tests.py"
# notify result of build to email address
notifications:
  email:
    - umar.toseef@eict.de
