mkdir tmp/ deploy/trusted/
python src/vendor/geni_trust/gen-certs.py tmp/
cp tmp/ca-cert.pem deploy/trusted/
cp tmp/sa-cert.pem deploy/trusted/
cp tmp/ma-cert.pem deploy/trusted/
cp tmp/root-*.pem admin/
cp tmp/*.pem test/creds/
cp tmp/*.xml test/creds/
rm -rf tmp/
